###
POST http://localhost:8080/orders
Content-Type: application/json
Authorization: Basic marek@example.org xxx

{
  "items": [
    {
      "bookId": 96,
      "quantity": 10
    },
    {
      "bookId": 59,
      "quantity": 11
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "marek@example.org"
  },
  "delivery": "COURIER"
}

###
GET http://localhost:8080/orders/119
Authorization: Basic admin xxx

###
PUT http://localhost:8080/orders/25/status
Content-Type: application/json

{
"status": "CANCELED"
}


###