###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 5,
      "quantity": 10
    },
    {
      "bookId": 7,
      "quantity": 11
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

###
GET http://localhost:8080/orders/18

###
PUT http://localhost:8080/orders/25/status
Content-Type: application/json

{
"status": "CANCELED"
}


###